"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { LandingNavbar } from "@/components/landing-navbar";

const overview = [
  ["Company Name", "TradeFinlytix"],
  ["Platform Type", "AI-Powered Financial Analytics & Intelligence Platform"],
  ["Focus Market", "Pakistan Stock Exchange (PSX)"],
  ["Founders", "Aleena Ahmed, Toqir Dar, Seerat Fatima, Ayan Ahmed"],
  ["Jurisdiction", "Islamic Republic of Pakistan"],
  ["Contact", "support@tradefinlytix.com"],
  ["Effective Date", "2025"],
];

const sections = [
  {
    id: "company-overview",
    title: "1. Company Overview",
    body: [
      "TradeFinlytix provides AI-driven analytics, predictive modeling, news intelligence, and decision-support tools for participants in the Pakistan Stock Exchange.",
      "The platform does not operate as a brokerage, investment advisor, asset manager, or financial institution.",
    ],
  },
  {
    id: "terms-of-service",
    title: "2. Terms of Service",
    groups: [
      {
        heading: "2.1 Acceptance of Terms",
        text: "By registering, accessing, or using the TradeFinlytix platform in any capacity, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service, our Privacy Policy, and any additional policies published by TradeFinlytix. If you do not agree, you must immediately cease use of the platform.",
      },
      {
        heading: "2.2 Eligibility",
        list: [
          "Be at least 18 years of age.",
          "Be legally capable of entering binding contracts under Pakistani law.",
          "Not be barred from accessing financial services by any regulatory authority.",
          "Use the platform solely for lawful purposes.",
        ],
      },
      {
        heading: "2.3 Account Registration & Security",
        text: "Users are responsible for providing accurate registration information, maintaining credential confidentiality, all activity under their account, and immediately notifying TradeFinlytix of unauthorized access at support@tradefinlytix.com.",
      },
      {
        heading: "2.4 Prohibited Conduct",
        list: [
          "Reverse-engineering, decompiling, or attempting to access platform source code.",
          "Scraping, harvesting, or bulk-downloading data using unauthorized automated means.",
          "Using AI-generated signals as the sole basis for high-volume automated trading.",
          "Reselling, redistributing, or sublicensing platform outputs without written authorization.",
          "Uploading false, misleading, or malicious content.",
          "Engaging in market manipulation, insider trading, or activity prohibited under Pakistani securities law.",
        ],
      },
    ],
  },
  {
    id: "ai-disclaimer",
    title: "3. AI & Predictive Analytics Disclaimer",
    callout: "AI predictions, buy/sell signals, and news summaries generated by TradeFinlytix are not financial advice. They are probabilistic model outputs and may be materially incorrect.",
    list: [
      "No guarantee is made regarding accuracy, completeness, or timeliness of AI-generated output.",
      "TradeFinlytix is not responsible for financial losses, missed opportunities, or damages from reliance on predictions or signals.",
      "The platform may be unavailable, delayed, or affected by third-party data source failures.",
      "All investments carry inherent risk, including risk of total capital loss.",
      "TradeFinlytix is not a SECP-registered investment advisor.",
    ],
  },
  {
    id: "privacy-policy",
    title: "4. Privacy Policy",
    groups: [
      {
        heading: "4.1 Data Collection",
        list: [
          "Identity Data: name and email address.",
          "Credentials: hashed password, never stored in plaintext.",
          "Usage Data: feature usage, watchlists, and query history.",
          "Technical Data: IP address, browser type, and device type.",
        ],
      },
      {
        heading: "4.2 Data We Do Not Collect",
        text: "TradeFinlytix does not collect CNIC or national identity numbers, bank account or brokerage credentials, payment card details, biometric data, or minors' data.",
      },
      {
        heading: "4.3 Legal Basis for Processing",
        list: [
          "Contract performance for delivering subscribed services.",
          "Legitimate interests for security, fraud prevention, and product improvement.",
          "Legal obligations under Pakistani law and regulatory requirements.",
          "Consent for optional marketing communications.",
        ],
      },
      {
        heading: "4.4 Data Retention",
        text: "Account data is retained for the duration of an active subscription plus 12 months after account closure, after which it is securely deleted or anonymized. Usage logs are retained for 6 months. Anonymized aggregate analytics may be retained indefinitely.",
      },
      {
        heading: "4.5 User Rights",
        text: "Users may request access, rectification, erasure, portability, or object to processing based on legitimate interests by contacting privacy@tradefinlytix.com.",
      },
    ],
  },
  {
    id: "legal-regulatory-compliance-framework",
    title: "5. Legal & Regulatory Compliance Framework",
    groups: [
      {
        heading: "5.1 Securities & Exchange Commission of Pakistan (SECP)",
        text: "TradeFinlytix operates as an analytics technology platform and not as a regulated entity under the Securities Act, 2015 or Companies Act, 2017. Platform outputs are labeled as AI-generated decision-support tools, and TradeFinlytix does not act as a broker, dealer, investment advisor, or collective investment scheme.",
      },
      {
        heading: "5.2 Pakistan Stock Exchange (PSX) Data Usage Policy",
        text: "TradeFinlytix uses PSX market data for internal model training and display purposes in accordance with PSX data dissemination policies. Users may not extract and redistribute raw market data obtained through the platform.",
      },
      {
        heading: "5.3 Prevention of Electronic Crimes Act, 2016 (PECA)",
        text: "Unauthorized access, disruption, data breaches, identity fraud, cyberfraud, or use of the platform to spread false financial information may result in immediate termination and reporting to the FIA Cyber Crime Wing.",
      },
      {
        heading: "5.4 State Bank of Pakistan (SBP) Regulations",
        text: "TradeFinlytix does not hold, transfer, or process user funds. Subscription payments are handled by compliant payment processors, and SBP-published macro data may be used as model inputs.",
      },
      {
        heading: "5.5 Personal Data Protection Bill / Draft Framework",
        text: "TradeFinlytix aligns its data practices with lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, integrity, and confidentiality principles.",
      },
      {
        heading: "5.6 AML & CFT",
        text: "TradeFinlytix does not process financial transactions between users or hold user funds. It will not knowingly provide services to sanctioned or watch-listed entities and may terminate accounts suspected of illegal financial activity.",
      },
    ],
  },
  {
    id: "intellectual-property",
    title: "6. Intellectual Property",
    body: [
      "All platform content, algorithms, model architectures, UI/UX designs, branding, documentation, AI/ML models, trained weights, RAG pipelines, datasets, feature engineering pipelines, and signal generation logic are the exclusive intellectual property of TradeFinlytix and its founders.",
      "Users receive a limited, non-exclusive, non-transferable license to access the platform under the applicable subscription tier. Reproduction, modification, redistribution, derivative works, scraping, API abuse, and unauthorized extraction are prohibited.",
    ],
  },
  {
    id: "subscription-payments-refunds",
    title: "7. Subscription, Payments & Refunds",
    groups: [
      {
        heading: "7.1 Billing",
        text: "Subscriptions are billed monthly or annually as selected at sign-up. Prices are displayed in Pakistani Rupees inclusive of applicable taxes. TradeFinlytix may revise pricing with 30 days advance notice to active subscribers.",
      },
      {
        heading: "7.2 Refund Policy",
        list: [
          "New subscribers may request a full refund within 7 calendar days if they have not materially used the platform.",
          "Renewal refund requests must be made within 3 days of the renewal charge.",
          "No refunds are issued for partial months, downgrades, or accounts terminated for Terms of Service violations.",
          "Enterprise contracts are governed by separate agreement terms.",
        ],
      },
      {
        heading: "7.3 Account Termination",
        text: "TradeFinlytix may suspend or terminate accounts for Terms violations, fraud, abuse, non-payment, or legal/regulatory requirement. Upon termination, access is revoked and data is handled according to Section 4.4.",
      },
    ],
  },
  {
    id: "governing-law",
    title: "8. Governing Law & Dispute Resolution",
    body: [
      "These Terms of Service and all related policies are governed by the laws of the Islamic Republic of Pakistan.",
      "Disputes shall first be addressed through good-faith negotiation within 30 days, then mediation through a mutually agreed mediator, and finally the exclusive jurisdiction of the courts of Lahore, Punjab, Pakistan.",
      "Users agree to bring claims in their individual capacity only, not as a plaintiff or class member in a class or representative proceeding.",
    ],
  },
  {
    id: "changes-to-policy",
    title: "9. Changes to This Policy",
    body: [
      "TradeFinlytix may update these policies at any time. Material changes will be published at least 14 days before effect, sent to registered users by email, and displayed through an in-platform banner.",
      "Continued use after the effective date of a revised policy constitutes acceptance of the new terms.",
    ],
  },
];

const contacts = [
  ["General Inquiries", "support@tradefinlytix.com"],
  ["Privacy & Data Rights", "privacy@tradefinlytix.com"],
  ["Legal & Compliance", "legal@tradefinlytix.com"],
  ["Security Reports", "security@tradefinlytix.com"],
  ["Business & Enterprise", "enterprise@tradefinlytix.com"],
];

export default function LegalPage() {
  const [mono, setMono] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;

    const updateMono = () => {
      setMono(
        document.documentElement.classList.contains("tfx-mono") ||
        localStorage.getItem("tfx_theme") === "mono"
      );
    };

    updateMono();

    const observer = new MutationObserver(updateMono);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });
    return () => observer.disconnect();
  }, []);

  return (
    <main className="legal-page">
      <LandingNavbar mono={mono} />
      <div style={{ height: 84 }} />
      <style>{`
        .legal-page { min-height: 100vh; background: #ffffff; color: #111827; font-family: 'DM Sans', 'Segoe UI', sans-serif; }
        .legal-page, .legal-header, .card, .toc, .legal-alert, .founder, .table-row span { transition: background 0.2s ease, border-color 0.2s ease, color 0.2s ease; }
        .legal-header { background: #f0fdf4; border-bottom: 1px solid #bbf7d0; padding: 28px 24px 64px; }
        .legal-nav { max-width: 1120px; margin: 0 auto 56px; display: flex; align-items: center; justify-content: space-between; gap: 18px; }
        .legal-brand { display: flex; align-items: center; gap: 10px; color: #111827; text-decoration: none; font-weight: 800; }
        .legal-links { display: flex; gap: 10px; flex-wrap: wrap; }
        .legal-links a { color: #374151; font-size: 14px; font-weight: 700; text-decoration: none; padding: 8px 12px; border-radius: 8px; }
        .legal-links a:hover { background: #dcfce7; color: #15803d; }
        .legal-hero { max-width: 1120px; margin: 0 auto; }
        .legal-kicker { display: inline-flex; padding: 6px 12px; border-radius: 999px; background: #dcfce7; border: 1px solid #bbf7d0; color: #15803d; font-size: 12px; font-weight: 800; }
        .legal-hero h1 { font-family: 'DM Serif Display', serif; font-size: clamp(38px, 6vw, 64px); line-height: 1.02; margin: 18px 0 14px; letter-spacing: -0.8px; }
        .legal-meta { color: #4b5563; line-height: 1.7; font-size: 15px; max-width: 760px; }
        .legal-wrap { max-width: 1120px; margin: -20px auto 0; padding: 56px 24px 84px; }
        .legal-alert { background: #fffbeb; border: 1.5px solid #f59e0b; border-radius: 14px; padding: 18px 20px; color: #78350f; font-weight: 700; line-height: 1.6; box-shadow: 0 18px 48px rgba(15,23,42,0.12); }
        .legal-grid { display: grid; grid-template-columns: 280px 1fr; gap: 28px; margin-top: 28px; align-items: start; }
        .toc { position: sticky; top: 24px; background: white; border: 1.5px solid #e5e7eb; border-radius: 14px; padding: 18px; }
        .toc h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 12px; }
        .toc a { display: block; color: #374151; text-decoration: none; font-size: 13px; font-weight: 700; padding: 8px 0; border-bottom: 1px solid #f1f5f9; }
        .toc a:hover { color: #16a34a; }
        .doc { display: flex; flex-direction: column; gap: 18px; }
        .card { background: white; border: 1.5px solid #e5e7eb; border-radius: 14px; padding: 24px; }
        .card h2 { font-size: 23px; margin-bottom: 14px; color: #0f172a; }
        .card h3 { font-size: 15px; margin: 18px 0 7px; color: #166534; }
        .card p { color: #4b5563; line-height: 1.75; margin-top: 10px; }
        .card ul { margin: 10px 0 0 20px; color: #4b5563; line-height: 1.75; }
        .overview-table, .contact-table { display: grid; border: 1px solid #e5e7eb; border-radius: 12px; overflow: hidden; }
        .table-row { display: grid; grid-template-columns: 220px 1fr; border-bottom: 1px solid #e5e7eb; }
        .table-row:last-child { border-bottom: none; }
        .table-row span { padding: 12px 14px; font-size: 14px; }
        .table-row span:first-child { background: #f0fdf4; color: #166534; font-weight: 800; }
        .inline-callout { background: #fef2f2; border: 1.5px solid #fecaca; color: #7f1d1d; border-radius: 12px; padding: 14px 16px; line-height: 1.65; font-weight: 700; margin: 12px 0; }
        .founders { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-top: 12px; }
        .founder { background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 12px; padding: 14px; font-weight: 800; color: #111827; }
        .founder span { display: block; color: #64748b; font-size: 12px; margin-top: 4px; }
        .legal-footer { color: #64748b; font-size: 13px; line-height: 1.7; }
        html.tfx-mono .legal-page { background: #0f172a; color: #f1f5f9; }
        html.tfx-mono .legal-header { background: #0a1f0a; border-bottom-color: #166534; }
        html.tfx-mono .legal-brand { color: #f1f5f9 !important; }
        html.tfx-mono .legal-links a { color: #cbd5e1 !important; }
        html.tfx-mono .legal-links a:hover { background: #1a2e1a; color: #4ade80 !important; }
        html.tfx-mono .legal-kicker { background: #14532d; border-color: #166534; color: #4ade80; }
        html.tfx-mono .legal-meta { color: #cbd5e1; }
        html.tfx-mono .legal-alert { background: #451a03; border-color: #92400e; color: #fde68a; box-shadow: 0 18px 48px rgba(0,0,0,0.35); }
        html.tfx-mono .toc,
        html.tfx-mono .card { background: #1e293b; border-color: #334155; }
        html.tfx-mono .toc h2,
        html.tfx-mono .legal-footer { color: #94a3b8; }
        html.tfx-mono .toc a { color: #cbd5e1 !important; border-bottom-color: #334155; }
        html.tfx-mono .toc a:hover { color: #4ade80 !important; }
        html.tfx-mono .card h2 { color: #f1f5f9; }
        html.tfx-mono .card h3 { color: #4ade80; }
        html.tfx-mono .card p,
        html.tfx-mono .card ul { color: #cbd5e1; }
        html.tfx-mono .overview-table,
        html.tfx-mono .contact-table { border-color: #334155; }
        html.tfx-mono .table-row { border-bottom-color: #334155; }
        html.tfx-mono .table-row span:first-child { background: #14532d; color: #4ade80; }
        html.tfx-mono .table-row span:last-child { color: #e2e8f0; }
        html.tfx-mono .inline-callout { background: #450a0a; border-color: #7f1d1d; color: #fecaca; }
        html.tfx-mono .founder { background: #111827; border-color: #334155; color: #f1f5f9; }
        html.tfx-mono .founder span { color: #94a3b8; }
        @media (max-width: 860px) { .legal-grid { grid-template-columns: 1fr; } .toc { position: static; } .founders { grid-template-columns: 1fr 1fr; } }
        @media (max-width: 560px) { .legal-nav { align-items: flex-start; flex-direction: column; } .table-row { grid-template-columns: 1fr; } .founders { grid-template-columns: 1fr; } }
      `}</style>

      <header className="legal-header">
        <section className="legal-hero">
          <span className="legal-kicker">Pakistan Stock Exchange AI Platform</span>
          <h1>Company Policy, Terms of Service & Legal Compliance</h1>
          <p className="legal-meta">
            Version 1.0 | Effective: 2025<br />
            Founders: Aleena Ahmed, Toqir Dar, Seerat Fatima, Ayan Ahmed
          </p>
        </section>
      </header>

      <div className="legal-wrap">
        <div className="legal-alert">
          Important: This document constitutes the binding legal framework governing use of the TradeFinlytix platform. By accessing or using the platform, you agree to these terms in full.
        </div>

        <div className="legal-grid">
          <aside className="toc">
            <h2>Contents</h2>
            <a href="#company-overview">Company Overview</a>
            <a href="#terms-of-service">Terms of Service</a>
            <a href="#ai-disclaimer">AI Disclaimer</a>
            <a href="#privacy-policy">Privacy Policy</a>
            <a href="#legal-regulatory-compliance-framework">Regulatory Compliance</a>
            <a href="#intellectual-property">Intellectual Property</a>
            <a href="#subscription-payments-refunds">Payments & Refunds</a>
            <a href="#contact-information">Contact</a>
          </aside>

          <div className="doc">
            <section className="card" id="company-overview">
              <h2>1. Company Overview</h2>
              <div className="overview-table">
                {overview.map(([label, value]) => (
                  <div className="table-row" key={label}>
                    <span>{label}</span>
                    <span>{value}</span>
                  </div>
                ))}
              </div>
              {sections[0].body?.map((text) => <p key={text}>{text}</p>)}
            </section>

            {sections.slice(1).map((section) => (
              <section className="card" id={section.id} key={section.id}>
                <h2>{section.title}</h2>
                {section.callout && <div className="inline-callout">{section.callout}</div>}
                {section.body?.map((text) => <p key={text}>{text}</p>)}
                {section.list && (
                  <ul>{section.list.map((item) => <li key={item}>{item}</li>)}</ul>
                )}
                {section.groups?.map((group) => (
                  <div key={group.heading}>
                    <h3>{group.heading}</h3>
                    {group.text && <p>{group.text}</p>}
                    {group.list && (
                      <ul>{group.list.map((item) => <li key={item}>{item}</li>)}</ul>
                    )}
                  </div>
                ))}
              </section>
            ))}

            <section className="card" id="contact-information">
              <h2>10. Contact Information</h2>
              <div className="contact-table">
                {contacts.map(([label, value]) => (
                  <div className="table-row" key={label}>
                    <span>{label}</span>
                    <span>{value}</span>
                  </div>
                ))}
              </div>
            </section>

            <section className="card" id="acknowledgement-adoption">
              <h2>11. Acknowledgement & Adoption</h2>
              <p>This Company Policy, Terms of Service & Legal Compliance document has been reviewed and adopted by the founding team of TradeFinlytix.</p>
              <div className="founders">
                {["Aleena Ahmed", "Toqir Dar", "Seerat Fatima", "Ayan Ahmed"].map((name) => (
                  <div className="founder" key={name}>{name}<span>Co-Founder</span></div>
                ))}
              </div>
              <p className="legal-footer">
                (c) 2025 TradeFinlytix. All Rights Reserved. This document is confidential and constitutes the official policy framework of TradeFinlytix. Unauthorized reproduction is prohibited.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
