"use client";

import { useEffect, useState } from "react";
import { motion, type Variants } from "framer-motion";
import { LandingNavbar } from "@/components/landing-navbar";
import {
  Building2, FileText, BrainCircuit, Lock, Scale, Fingerprint,
  CreditCard, Gavel, RefreshCw, Mail, Users, AlertTriangle, ChevronRight
} from "lucide-react";

const EASE: [number, number, number, number] = [0.22, 1, 0.36, 1];
const fadeUp: Variants = {
  hidden: { opacity: 0, y: 28 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: EASE } },
};
const stagger: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.09 } },
};

const overview = [
  ["Company Name", "TradeFinlytix"],
  ["Platform Type", "AI-Powered Financial Analytics & Intelligence Platform"],
  ["Focus Market", "Pakistan Stock Exchange (PSX)"],
  ["Founders", "Aleena Ahmed, Toqir Dar, Seerat Fatima, Ayan Ahmed"],
  ["Jurisdiction", "Islamic Republic of Pakistan"],
  ["Contact", "support@tradefinlytix.com"],
  ["Effective Date", "2025"],
];

const contacts = [
  ["General Inquiries", "support@tradefinlytix.com"],
  ["Privacy & Data Rights", "privacy@tradefinlytix.com"],
  ["Legal & Compliance", "legal@tradefinlytix.com"],
  ["Security Reports", "security@tradefinlytix.com"],
  ["Business & Enterprise", "enterprise@tradefinlytix.com"],
];

const sections = [
  {
    id: "company-overview",
    title: "Company Overview",
    num: "1",
    Icon: Building2,
    accent: "#16A34A",
    darkAccent: "#4ade80",
    lightBg: "#f0fdf4",
    darkBg: "#0a1f0a",
    body: [
      "TradeFinlytix provides AI-driven analytics, predictive modeling, news intelligence, and decision-support tools for participants in the Pakistan Stock Exchange.",
      "The platform does not operate as a brokerage, investment advisor, asset manager, or financial institution.",
    ],
  },
  {
    id: "terms-of-service",
    title: "Terms of Service",
    num: "2",
    Icon: FileText,
    accent: "#1D4ED8",
    darkAccent: "#60a5fa",
    lightBg: "#eff6ff",
    darkBg: "#0d1a2e",
    groups: [
      {
        heading: "2.1 Acceptance of Terms",
        text: "By registering, accessing, or using the TradeFinlytix platform in any capacity, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service, our Privacy Policy, and any additional policies published by TradeFinlytix. If you do not agree, you must immediately cease use of the platform.",
      },
      {
        heading: "2.2 Eligibility",
        list: [
          "Be at least 18 years of age.",
          "Be legally capable of entering binding contracts under Pakistani law.",
          "Not be barred from accessing financial services by any regulatory authority.",
          "Use the platform solely for lawful purposes.",
        ],
      },
      {
        heading: "2.3 Account Registration & Security",
        text: "Users are responsible for providing accurate registration information, maintaining credential confidentiality, all activity under their account, and immediately notifying TradeFinlytix of unauthorized access at support@tradefinlytix.com.",
      },
      {
        heading: "2.4 Prohibited Conduct",
        list: [
          "Reverse-engineering, decompiling, or attempting to access platform source code.",
          "Scraping, harvesting, or bulk-downloading data using unauthorized automated means.",
          "Using AI-generated signals as the sole basis for high-volume automated trading.",
          "Reselling, redistributing, or sublicensing platform outputs without written authorization.",
          "Uploading false, misleading, or malicious content.",
          "Engaging in market manipulation, insider trading, or activity prohibited under Pakistani securities law.",
        ],
      },
    ],
  },
  {
    id: "ai-disclaimer",
    title: "AI & Predictive Analytics Disclaimer",
    num: "3",
    Icon: BrainCircuit,
    accent: "#92400E",
    darkAccent: "#fb923c",
    lightBg: "#fffbeb",
    darkBg: "#1c0f00",
    callout: "AI predictions, buy/sell signals, and news summaries generated by TradeFinlytix are not financial advice. They are probabilistic model outputs and may be materially incorrect.",
    list: [
      "No guarantee is made regarding accuracy, completeness, or timeliness of AI-generated output.",
      "TradeFinlytix is not responsible for financial losses, missed opportunities, or damages from reliance on predictions or signals.",
      "The platform may be unavailable, delayed, or affected by third-party data source failures.",
      "All investments carry inherent risk, including risk of total capital loss.",
      "TradeFinlytix is not a SECP-registered investment advisor.",
    ],
  },
  {
    id: "privacy-policy",
    title: "Privacy Policy",
    num: "4",
    Icon: Lock,
    accent: "#15803D",
    darkAccent: "#4ade80",
    lightBg: "#f0fdf4",
    darkBg: "#0a1f0a",
    groups: [
      {
        heading: "4.1 Data Collection",
        list: [
          "Identity Data: name and email address.",
          "Credentials: hashed password, never stored in plaintext.",
          "Usage Data: feature usage, watchlists, and query history.",
          "Technical Data: IP address, browser type, and device type.",
        ],
      },
      {
        heading: "4.2 Data We Do Not Collect",
        text: "TradeFinlytix does not collect CNIC or national identity numbers, bank account or brokerage credentials, payment card details, biometric data, or minors' data.",
      },
      {
        heading: "4.3 Legal Basis for Processing",
        list: [
          "Contract performance for delivering subscribed services.",
          "Legitimate interests for security, fraud prevention, and product improvement.",
          "Legal obligations under Pakistani law and regulatory requirements.",
          "Consent for optional marketing communications.",
        ],
      },
      {
        heading: "4.4 Data Retention",
        text: "Account data is retained for the duration of an active subscription plus 12 months after account closure, after which it is securely deleted or anonymized. Usage logs are retained for 6 months. Anonymized aggregate analytics may be retained indefinitely.",
      },
      {
        heading: "4.5 User Rights",
        text: "Users may request access, rectification, erasure, portability, or object to processing based on legitimate interests by contacting privacy@tradefinlytix.com.",
      },
    ],
  },
  {
    id: "legal-regulatory-compliance-framework",
    title: "Legal & Regulatory Compliance",
    num: "5",
    Icon: Scale,
    accent: "#7C3AED",
    darkAccent: "#a78bfa",
    lightBg: "#f5f3ff",
    darkBg: "#160d2e",
    groups: [
      {
        heading: "5.1 Securities & Exchange Commission of Pakistan (SECP)",
        text: "TradeFinlytix operates as an analytics technology platform and not as a regulated entity under the Securities Act, 2015 or Companies Act, 2017. Platform outputs are labeled as AI-generated decision-support tools, and TradeFinlytix does not act as a broker, dealer, investment advisor, or collective investment scheme.",
      },
      {
        heading: "5.2 Pakistan Stock Exchange (PSX) Data Usage Policy",
        text: "TradeFinlytix uses PSX market data for internal model training and display purposes in accordance with PSX data dissemination policies. Users may not extract and redistribute raw market data obtained through the platform.",
      },
      {
        heading: "5.3 Prevention of Electronic Crimes Act, 2016 (PECA)",
        text: "Unauthorized access, disruption, data breaches, identity fraud, cyberfraud, or use of the platform to spread false financial information may result in immediate termination and reporting to the FIA Cyber Crime Wing.",
      },
      {
        heading: "5.4 State Bank of Pakistan (SBP) Regulations",
        text: "TradeFinlytix does not hold, transfer, or process user funds. Subscription payments are handled by compliant payment processors, and SBP-published macro data may be used as model inputs.",
      },
      {
        heading: "5.5 Personal Data Protection Bill / Draft Framework",
        text: "TradeFinlytix aligns its data practices with lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, integrity, and confidentiality principles.",
      },
      {
        heading: "5.6 AML & CFT",
        text: "TradeFinlytix does not process financial transactions between users or hold user funds. It will not knowingly provide services to sanctioned or watch-listed entities and may terminate accounts suspected of illegal financial activity.",
      },
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    num: "6",
    Icon: Fingerprint,
    accent: "#0891B2",
    darkAccent: "#22d3ee",
    lightBg: "#ecfeff",
    darkBg: "#041a1f",
    body: [
      "All platform content, algorithms, model architectures, UI/UX designs, branding, documentation, AI/ML models, trained weights, RAG pipelines, datasets, feature engineering pipelines, and signal generation logic are the exclusive intellectual property of TradeFinlytix and its founders.",
      "Users receive a limited, non-exclusive, non-transferable license to access the platform under the applicable subscription tier. Reproduction, modification, redistribution, derivative works, scraping, API abuse, and unauthorized extraction are prohibited.",
    ],
  },
  {
    id: "subscription-payments-refunds",
    title: "Subscription, Payments & Refunds",
    num: "7",
    Icon: CreditCard,
    accent: "#16A34A",
    darkAccent: "#4ade80",
    lightBg: "#f0fdf4",
    darkBg: "#0a1f0a",
    groups: [
      {
        heading: "7.1 Billing",
        text: "Subscriptions are billed monthly or annually as selected at sign-up. Prices are displayed in Pakistani Rupees inclusive of applicable taxes. TradeFinlytix may revise pricing with 30 days advance notice to active subscribers.",
      },
      {
        heading: "7.2 Refund Policy",
        list: [
          "New subscribers may request a full refund within 7 calendar days if they have not materially used the platform.",
          "Renewal refund requests must be made within 3 days of the renewal charge.",
          "No refunds are issued for partial months, downgrades, or accounts terminated for Terms of Service violations.",
          "Enterprise contracts are governed by separate agreement terms.",
        ],
      },
      {
        heading: "7.3 Account Termination",
        text: "TradeFinlytix may suspend or terminate accounts for Terms violations, fraud, abuse, non-payment, or legal/regulatory requirement. Upon termination, access is revoked and data is handled according to Section 4.4.",
      },
    ],
  },
  {
    id: "governing-law",
    title: "Governing Law & Dispute Resolution",
    num: "8",
    Icon: Gavel,
    accent: "#B45309",
    darkAccent: "#fbbf24",
    lightBg: "#fffbeb",
    darkBg: "#1c1000",
    body: [
      "These Terms of Service and all related policies are governed by the laws of the Islamic Republic of Pakistan.",
      "Disputes shall first be addressed through good-faith negotiation within 30 days, then mediation through a mutually agreed mediator, and finally the exclusive jurisdiction of the courts of Lahore, Punjab, Pakistan.",
      "Users agree to bring claims in their individual capacity only, not as a plaintiff or class member in a class or representative proceeding.",
    ],
  },
  {
    id: "changes-to-policy",
    title: "Changes to This Policy",
    num: "9",
    Icon: RefreshCw,
    accent: "#1D4ED8",
    darkAccent: "#60a5fa",
    lightBg: "#eff6ff",
    darkBg: "#0d1a2e",
    body: [
      "TradeFinlytix may update these policies at any time. Material changes will be published at least 14 days before effect, sent to registered users by email, and displayed through an in-platform banner.",
      "Continued use after the effective date of a revised policy constitutes acceptance of the new terms.",
    ],
  },
];

// Hero right-side preview items
const heroPreviewItems = [
  { label: "Terms of Service", Icon: FileText, color: "#1D4ED8" },
  { label: "Privacy Policy", Icon: Lock, color: "#15803D" },
  { label: "AI Disclaimer", Icon: BrainCircuit, color: "#92400E" },
  { label: "Regulatory Compliance", Icon: Scale, color: "#7C3AED" },
];

export default function LegalPage() {
  const [mono, setMono] = useState(false);
  const [activeSection, setActiveSection] = useState(0);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const updateMono = () => {
      setMono(
        document.documentElement.classList.contains("tfx-mono") ||
        localStorage.getItem("tfx_theme") === "mono"
      );
    };
    updateMono();
    const observer = new MutationObserver(updateMono);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });
    return () => observer.disconnect();
  }, []);

  const th = {
    bg: mono ? "#0f172a" : "#ffffff",
    text: mono ? "#f1f5f9" : "#111827",
    subtext: mono ? "#94a3b8" : "#4b5563",
    muted: mono ? "#64748b" : "#6b7280",
    card: mono ? "#1e293b" : "#ffffff",
    border: mono ? "#334155" : "#e5e7eb",
    borderSubtle: mono ? "#1e293b" : "#f1f5f9",
    sectionAlt: mono ? "#111827" : "#f8fafc",
    heroBg: mono ? "linear-gradient(135deg, #0a1f0a 0%, #0f172a 100%)" : "linear-gradient(135deg, #f0fdf4 0%, #dcfce7 55%, #bbf7d0 100%)",
    heroBorder: mono ? "#166534" : "#bbf7d0",
    kicker: { bg: mono ? "#14532d" : "#dcfce7", border: mono ? "#166534" : "#bbf7d0", color: mono ? "#4ade80" : "#15803d" },
    toc: { bg: mono ? "#111827" : "#ffffff" },
    tableHead: { bg: mono ? "#14532d" : "#f0fdf4", color: mono ? "#4ade80" : "#166534" },
    tableRow: { border: mono ? "#334155" : "#e5e7eb" },
    callout: { bg: mono ? "#450a0a" : "#fef2f2", border: mono ? "#7f1d1d" : "#fecaca", color: mono ? "#fecaca" : "#7f1d1d" },
    alert: { bg: mono ? "#1c1000" : "#fffbeb", border: mono ? "#92400e" : "#f59e0b", color: mono ? "#fde68a" : "#78350f" },
    founder: { bg: mono ? "#111827" : "#f8fafc", border: mono ? "#334155" : "#e5e7eb", color: mono ? "#f1f5f9" : "#111827", sub: mono ? "#94a3b8" : "#64748b" },
  };

  return (
    <main style={{ minHeight: "100vh", background: th.bg, color: th.text, fontFamily: "'DM Sans','Segoe UI',sans-serif", transition: "background 0.2s ease, color 0.2s ease" }}>
      <LandingNavbar mono={mono} />
      <div style={{ height: 84 }} />

      {/* ── Hero ── */}
      <header style={{ background: th.heroBg, borderBottom: `1px solid ${th.heroBorder}`, padding: "72px 24px 80px", position: "relative", overflow: "hidden", transition: "background 0.2s ease" }}>
        {/* blobs */}
        <div style={{ position: "absolute", top: -100, right: -100, width: 440, height: 440, borderRadius: "50%", background: mono ? "radial-gradient(circle,rgba(74,222,128,0.07) 0%,transparent 70%)" : "radial-gradient(circle,rgba(22,163,74,0.12) 0%,transparent 70%)", pointerEvents: "none" }} />
        <div style={{ position: "absolute", bottom: -80, left: "25%", width: 320, height: 320, borderRadius: "50%", background: mono ? "radial-gradient(circle,rgba(74,222,128,0.04) 0%,transparent 70%)" : "radial-gradient(circle,rgba(22,163,74,0.07) 0%,transparent 70%)", pointerEvents: "none" }} />

        <div className="hero-two-col" style={{ maxWidth: 1120, margin: "0 auto", position: "relative", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 64, alignItems: "center" }}>

          {/* LEFT */}
          <motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, ease: EASE }}>
            <motion.span
              initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.5, ease: EASE, delay: 0.1 }}
              style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 999, background: th.kicker.bg, border: `1px solid ${th.kicker.border}`, color: th.kicker.color, fontSize: 12, fontWeight: 800, letterSpacing: "0.04em", textTransform: "uppercase" as const, marginBottom: 22 }}
            >
              Pakistan Stock Exchange AI Platform
            </motion.span>

            <motion.h1
              initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65, ease: EASE, delay: 0.15 }}
              style={{ fontFamily: "'DM Serif Display', serif", fontSize: "clamp(36px, 4.5vw, 60px)", lineHeight: 1.06, letterSpacing: "-1px", margin: "0 0 20px", color: th.text, fontWeight: 700 }}
            >
              Company Policy,{" "}
              <span style={{ color: "#16A34A" }}>Terms</span>
              {" "}& Legal
              <br />
              <span style={{ color: "#16A34A" }}>Compliance</span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, ease: EASE, delay: 0.25 }}
              style={{ fontSize: 15.5, color: th.subtext, lineHeight: 1.75, maxWidth: 460, margin: "0 0 36px" }}
            >
              Version 1.0 · Effective 2025. The binding legal framework governing use of the TradeFinlytix platform on the Pakistan Stock Exchange.
            </motion.p>

            {/* stats */}
            <motion.div
              initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, ease: EASE, delay: 0.35 }}
              style={{ display: "flex", gap: 36, flexWrap: "wrap" as const }}
            >
              {[
                { label: "Sections", value: "11" },
                { label: "Founders", value: "4" },
                { label: "Version", value: "1.0" },
              ].map((stat) => (
                <div key={stat.label} style={{ display: "flex", flexDirection: "column" as const, gap: 3 }}>
                  <span style={{ fontFamily: "'DM Serif Display', serif", fontSize: 32, color: "#16A34A", lineHeight: 1, fontWeight: 700 }}>{stat.value}</span>
                  <span style={{ fontSize: 12, color: th.muted, fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: "0.04em" }}>{stat.label}</span>
                </div>
              ))}
            </motion.div>
          </motion.div>

          {/* RIGHT — preview cards */}
          <motion.div
            className="hero-right-cards"
            style={{ display: "flex", flexDirection: "column" as const, gap: 12, position: "relative" as const }}
            initial={{ opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7, ease: EASE, delay: 0.2 }}
          >
            <div style={{ position: "absolute" as const, top: -18, right: 0, background: mono ? "#14532d" : "#16A34A", color: "#fff", fontSize: 11, fontWeight: 800, padding: "4px 12px", borderRadius: 999, letterSpacing: "0.06em" }}>
              DOCUMENT OVERVIEW
            </div>

            {heroPreviewItems.map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: 30 }}
                animate={{ opacity: 1, x: i % 2 === 1 ? 16 : 0 }}
                transition={{ duration: 0.55, ease: EASE, delay: 0.3 + i * 0.1 }}
                whileHover={{ scale: 1.02, boxShadow: mono ? "0 8px 28px rgba(0,0,0,0.4)" : "0 8px 28px rgba(22,163,74,0.15)", transition: { duration: 0.2 } }}
                style={{ background: mono ? "rgba(30,41,59,0.85)" : "rgba(255,255,255,0.9)", backdropFilter: "blur(8px)", border: `1.5px solid ${th.border}`, borderRadius: 12, padding: "16px 18px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, boxShadow: mono ? "0 4px 16px rgba(0,0,0,0.25)" : "0 4px 16px rgba(0,0,0,0.06)", cursor: "default" }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                  <div style={{ width: 36, height: 36, borderRadius: 10, background: `${item.color}18`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                    <item.Icon size={17} color={item.color} strokeWidth={2} />
                  </div>
                  <span style={{ fontSize: 14, fontWeight: 700, color: mono ? "#e2e8f0" : "#111827" }}>{item.label}</span>
                </div>
                <ChevronRight size={15} color={th.muted} />
              </motion.div>
            ))}

            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.85, duration: 0.5 }} style={{ textAlign: "center" as const, marginTop: 4 }}>
              <span style={{ fontSize: 12, color: th.muted, fontWeight: 600 }}>+ 7 more sections below ↓</span>
            </motion.div>
          </motion.div>
        </div>
      </header>

      {/* ── Alert banner ── */}
      <motion.div
        initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, ease: EASE, delay: 0.5 }}
        style={{ maxWidth: 1120, margin: "0 auto", padding: "24px 24px 0" }}
      >
        <div style={{ background: th.alert.bg, border: `1.5px solid ${th.alert.border}`, borderRadius: 14, padding: "16px 20px", color: th.alert.color, fontWeight: 700, lineHeight: 1.65, fontSize: 14, display: "flex", alignItems: "flex-start", gap: 12, transition: "background 0.2s ease, border-color 0.2s ease, color 0.2s ease" }}>
          <AlertTriangle size={18} style={{ flexShrink: 0, marginTop: 2 }} />
          <span>Important: This document constitutes the binding legal framework governing use of the TradeFinlytix platform. By accessing or using the platform, you agree to these terms in full.</span>
        </div>
      </motion.div>

      {/* ── Main content ── */}
       <div style={{ maxWidth: 1120, margin: "0 auto", padding: "40px 24px 100px", display: "grid", gridTemplateColumns: "260px 1fr", gap: 40, alignItems: "start" }}>

        {/* Sidebar TOC */}
        <motion.aside
          initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.6, ease: EASE, delay: 0.4 }}
          style={{ position: "sticky", top: 24, background: th.toc.bg, border: `1.5px solid ${th.border}`, borderRadius: 16, padding: "20px", transition: "background 0.2s ease" }}
        >
          <p style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase" as const, color: th.muted, marginBottom: 16 }}>Contents</p>

          {sections.map((s, i) => {
            const active = activeSection === i;
            const color = mono ? s.darkAccent : s.accent;
            return (
              <a
                key={s.id}
                href={`#${s.id}`}
                onClick={() => setActiveSection(i)}
                style={{ display: "flex", alignItems: "center", gap: 9, padding: "9px 10px", borderRadius: 10, textDecoration: "none", fontSize: 12.5, fontWeight: active ? 700 : 500, color: active ? color : th.subtext, background: active ? (mono ? s.darkBg : s.lightBg) : "transparent", marginBottom: 3, transition: "background 0.15s, color 0.15s" }}
              >
                <s.Icon size={13} strokeWidth={2.2} color={active ? color : undefined} />
                <span style={{ lineHeight: 1.3 }}>{s.num}. {s.title}</span>
              </a>
            );
          })}

          {/* extra links */}
          {[
            { label: "10. Contact Information", href: "#contact-information" },
            { label: "11. Acknowledgement", href: "#acknowledgement-adoption" },
          ].map((link) => (
            <a key={link.href} href={link.href} style={{ display: "flex", alignItems: "center", gap: 9, padding: "9px 10px", borderRadius: 10, textDecoration: "none", fontSize: 12.5, fontWeight: 500, color: th.subtext, marginBottom: 3, transition: "color 0.15s" }}>
              <Mail size={13} strokeWidth={2.2} />
              <span>{link.label}</span>
            </a>
          ))}

          <div style={{ marginTop: 18, paddingTop: 14, borderTop: `1px solid ${th.borderSubtle}` }}>
            <p style={{ fontSize: 12, color: th.muted, lineHeight: 1.6 }}>
              Questions?{" "}
              <a href="mailto:legal@tradefinlytix.com" style={{ color: "#16A34A", fontWeight: 700, textDecoration: "none" }}>
                legal@tradefinlytix.com →
              </a>
            </p>
          </div>
        </motion.aside>

        {/* Sections */}
        <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

          {/* Company Overview card */}
          <motion.section
            id="company-overview"
            style={{ scrollMarginTop: 80, background: th.card, border: `1.5px solid ${th.border}`, borderRadius: 18, padding: "28px", transition: "background 0.2s ease, border-color 0.2s ease" }}
            initial={{ opacity: 0, y: 36 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.6, ease: EASE }}
          >
            <SectionHeader num="1" title="Company Overview" Icon={Building2} accent="#16A34A" darkAccent="#4ade80" lightBg="#f0fdf4" darkBg="#0a1f0a" mono={mono} />

            {/* Overview table */}
            <div style={{ border: `1px solid ${th.border}`, borderRadius: 12, overflow: "hidden", marginBottom: 16, transition: "border-color 0.2s" }}>
              {overview.map(([label, value], i) => (
                <div key={label} style={{ display: "grid", gridTemplateColumns: "200px 1fr", borderBottom: i < overview.length - 1 ? `1px solid ${th.border}` : "none", transition: "border-color 0.2s" }}>
                  <span style={{ padding: "12px 14px", fontSize: 13.5, background: mono ? "#14532d" : "#f0fdf4", color: mono ? "#4ade80" : "#166534", fontWeight: 800, transition: "background 0.2s, color 0.2s" }}>{label}</span>
                  <span style={{ padding: "12px 14px", fontSize: 13.5, color: th.subtext, transition: "color 0.2s" }}>{value}</span>
                </div>
              ))}
            </div>
            {sections[0].body?.map((text) => (
              <p key={text} style={{ color: th.subtext, lineHeight: 1.75, fontSize: 14.5, margin: "10px 0 0" }}>{text}</p>
            ))}
          </motion.section>

          {/* Dynamic sections */}
          {sections.slice(1).map((section, idx) => (
            <motion.section
              key={section.id}
              id={section.id}
              style={{ scrollMarginTop: 80, background: th.card, border: `1.5px solid ${th.border}`, borderRadius: 18, padding: "28px", transition: "background 0.2s ease, border-color 0.2s ease" }}
              initial={{ opacity: 0, y: 36 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.6, ease: EASE, delay: 0.05 }}
            >
              <SectionHeader num={section.num} title={section.title} Icon={section.Icon} accent={section.accent} darkAccent={section.darkAccent} lightBg={section.lightBg} darkBg={section.darkBg} mono={mono} />

              {section.callout && (
                <div style={{ background: th.callout.bg, border: `1.5px solid ${th.callout.border}`, color: th.callout.color, borderRadius: 12, padding: "14px 16px", lineHeight: 1.65, fontWeight: 700, fontSize: 14, marginBottom: 18, display: "flex", gap: 10, alignItems: "flex-start", transition: "background 0.2s, border-color 0.2s, color 0.2s" }}>
                  <AlertTriangle size={16} style={{ flexShrink: 0, marginTop: 2 }} />
                  {section.callout}
                </div>
              )}

              {section.body?.map((text) => (
                <p key={text} style={{ color: th.subtext, lineHeight: 1.75, fontSize: 14.5, margin: "10px 0 0" }}>{text}</p>
              ))}

              {section.list && (
                <motion.ul
                  variants={stagger} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-40px" }}
                  style={{ margin: "14px 0 0", paddingLeft: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 8 }}
                >
                  {section.list.map((item) => (
                    <motion.li key={item} variants={fadeUp} style={{ display: "flex", alignItems: "flex-start", gap: 10, color: th.subtext, fontSize: 14.5, lineHeight: 1.7 }}>
                      <span style={{ width: 6, height: 6, borderRadius: "50%", background: mono ? section.darkAccent : section.accent, flexShrink: 0, marginTop: 8 }} />
                      {item}
                    </motion.li>
                  ))}
                </motion.ul>
              )}

              {section.groups?.map((group) => (
                <div key={group.heading} style={{ marginTop: 20 }}>
                  <h3 style={{ fontSize: 14.5, fontWeight: 800, color: mono ? section.darkAccent : section.accent, margin: "0 0 8px", letterSpacing: "0.01em" }}>{group.heading}</h3>
                  {group.text && <p style={{ color: th.subtext, lineHeight: 1.75, fontSize: 14.5, margin: 0 }}>{group.text}</p>}
                  {group.list && (
                    <motion.ul
                      variants={stagger} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-40px" }}
                      style={{ margin: "10px 0 0", paddingLeft: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 7 }}
                    >
                      {group.list.map((item) => (
                        <motion.li key={item} variants={fadeUp} style={{ display: "flex", alignItems: "flex-start", gap: 10, color: th.subtext, fontSize: 14.5, lineHeight: 1.7 }}>
                          <span style={{ width: 6, height: 6, borderRadius: "50%", background: mono ? section.darkAccent : section.accent, flexShrink: 0, marginTop: 8 }} />
                          {item}
                        </motion.li>
                      ))}
                    </motion.ul>
                  )}
                </div>
              ))}
            </motion.section>
          ))}

          {/* Contact card */}
          <motion.section
            id="contact-information"
            style={{ scrollMarginTop: 80, background: th.card, border: `1.5px solid ${th.border}`, borderRadius: 18, padding: "28px", transition: "background 0.2s ease, border-color 0.2s ease" }}
            initial={{ opacity: 0, y: 36 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.6, ease: EASE }}
          >
            <SectionHeader num="10" title="Contact Information" Icon={Mail} accent="#16A34A" darkAccent="#4ade80" lightBg="#f0fdf4" darkBg="#0a1f0a" mono={mono} />
            <div style={{ border: `1px solid ${th.border}`, borderRadius: 12, overflow: "hidden", transition: "border-color 0.2s" }}>
              {contacts.map(([label, value], i) => (
                <div key={label} style={{ display: "grid", gridTemplateColumns: "220px 1fr", borderBottom: i < contacts.length - 1 ? `1px solid ${th.border}` : "none", transition: "border-color 0.2s" }}>
                  <span style={{ padding: "13px 14px", fontSize: 13.5, background: mono ? "#14532d" : "#f0fdf4", color: mono ? "#4ade80" : "#166534", fontWeight: 800, transition: "background 0.2s, color 0.2s" }}>{label}</span>
                  <span style={{ padding: "13px 14px", fontSize: 13.5, color: "#16A34A", fontWeight: 600 }}>
                    <a href={`mailto:${value}`} style={{ color: "inherit", textDecoration: "none" }}>{value}</a>
                  </span>
                </div>
              ))}
            </div>
          </motion.section>

          {/* Acknowledgement card */}
          <motion.section
            id="acknowledgement-adoption"
            style={{ scrollMarginTop: 80, background: th.card, border: `1.5px solid ${th.border}`, borderRadius: 18, padding: "28px", transition: "background 0.2s ease, border-color 0.2s ease" }}
            initial={{ opacity: 0, y: 36 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.6, ease: EASE }}
          >
            <SectionHeader num="11" title="Acknowledgement & Adoption" Icon={Users} accent="#16A34A" darkAccent="#4ade80" lightBg="#f0fdf4" darkBg="#0a1f0a" mono={mono} />
            <p style={{ color: th.subtext, lineHeight: 1.75, fontSize: 14.5, margin: "0 0 20px" }}>
              This Company Policy, Terms of Service & Legal Compliance document has been reviewed and adopted by the founding team of TradeFinlytix.
            </p>

            <motion.div
              style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 12, marginBottom: 24 }}
              variants={stagger} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-40px" }}
            >
              {["Aleena Ahmed", "Toqir Dar", "Seerat Fatima", "Ayan Ahmed"].map((name) => (
                <motion.div
                  key={name}
                  variants={fadeUp}
                  whileHover={{ y: -3, boxShadow: mono ? "0 8px 24px rgba(0,0,0,0.4)" : "0 8px 24px rgba(22,163,74,0.12)", transition: { duration: 0.2 } }}
                  style={{ background: th.founder.bg, border: `1px solid ${th.founder.border}`, borderRadius: 14, padding: "16px", transition: "background 0.2s, border-color 0.2s" }}
                >
                  <div style={{ width: 36, height: 36, borderRadius: 10, background: "#dcfce7", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 10 }}>
                    <Users size={16} color="#16A34A" strokeWidth={2} />
                  </div>
                  <div style={{ fontWeight: 800, fontSize: 13.5, color: th.founder.color, lineHeight: 1.3 }}>{name}</div>
                  <div style={{ fontSize: 12, color: th.founder.sub, marginTop: 4, fontWeight: 600 }}>Co-Founder</div>
                </motion.div>
              ))}
            </motion.div>

            <div style={{ background: th.sectionAlt, border: `1.5px solid ${th.border}`, borderRadius: 12, padding: "16px 18px", color: th.muted, fontSize: 13, lineHeight: 1.7, transition: "background 0.2s, border-color 0.2s" }}>
              © 2025 TradeFinlytix. All Rights Reserved. This document is confidential and constitutes the official policy framework of TradeFinlytix. Unauthorized reproduction is prohibited.
            </div>
          </motion.section>
        </div>
      </div>

      <style>{`
         @media (max-width: 860px) {
          .hero-two-col { grid-template-columns: 1fr !important; gap: 40px !important; }
          .hero-right-cards { display: none !important; }
        }
        * { box-sizing: border-box; }
        a:focus-visible { outline: 2px solid #16A34A; outline-offset: 2px; }
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 99px; }
      `}</style>
    </main>
  );
}

// Reusable section header
function SectionHeader({ num, title, Icon, accent, darkAccent, lightBg, darkBg, mono }: {
  num: string; title: string; Icon: React.ElementType;
  accent: string; darkAccent: string; lightBg: string; darkBg: string; mono: boolean;
}) {
  const color = mono ? darkAccent : accent;
  return (
    <motion.div
      style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 22, paddingBottom: 18, borderBottom: `1.5px solid ${mono ? "#1e293b" : "#f1f5f9"}` }}
      initial={{ opacity: 0, x: -16 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.5, ease: [0.22,1,0.36,1] }}
    >
      <motion.div
        whileHover={{ rotate: [0, -8, 8, 0], scale: 1.1 }} transition={{ duration: 0.4 }}
        style={{ width: 44, height: 44, borderRadius: 12, background: mono ? darkBg : lightBg, border: `1.5px solid ${color}33`, display: "flex", alignItems: "center", justifyContent: "center", color, flexShrink: 0 }}
      >
        <Icon size={20} strokeWidth={2} />
      </motion.div>
      <div>
        <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.07em", textTransform: "uppercase" as const, color, marginBottom: 3 }}>Section {num}</div>
        <h2 style={{ fontFamily: "'DM Serif Display', serif", fontSize: 24, fontWeight: 700, color: mono ? "#f1f5f9" : "#0f172a", margin: 0, lineHeight: 1.2 }}>{title}</h2>
      </div>
    </motion.div>
  );
}
